services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REST_API=http://localhost:9000
    ports:
      - '9005:3000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:5000'
    volumes:
      - ./backend/data:/data
