version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '9005:3000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./backend/data:/data
