import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UniClOGS Mission Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          UniClOGS Mission Server
        </h1>

        <div className={styles.grid}>
          <a href="/map" className={styles.card}>
            <h2>Map &rarr;</h2>
            <p>A graphical view of OreSat0's active location and orbit.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://oresat.org/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Maintained by the Portland State Aerospace Society
          <span className={styles.logo}>
            <Image src="/oresat-patch.png" alt="OreSat Logo" width={32} height={25} />
          </span>
        </a>
      </footer>
    </div>
  )
}
